name: 'Release: Notify in Slack when a new (pre)release is published'
on:
  #release:
  #  types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version.'
        required: true
  pull_request:

jobs:
  #notify-release-published:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: 'Notify to Slack when a new release is published'
  #      if: ${{ 'false' && !contains(github.event.release.tag_name, 'wc-beta-tester') }}
  #      uses: archive/github-actions-slack@v2.10.0
  #      with:
  #        slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
  #        slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }},${{ secrets.WOO_ANNOUNCEMENTS_SLACK_CHANNEL }}
  #        slack-optional-unfurl_links: false
  #        slack-text: |
  #          :woo-bounce: *<${{ github.event.release.html_url }}|WooCommerce ${{ github.event.release.name }}>* has been released! :rocket:
  #
  #          (<@woo-developer-advocacy-team> could you publish the release post? :ty:)

  run-canonical-extensions-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run tests on the canonical extensions'
        shell: bash
        env:
            # TODO: move from vars to secrets after testing is complete
            CANONICAL_EXTENSIONS: ${{ vars.CANONICAL_EXTENSIONS }}
            # TODO: use PAT, so the script can reach max of orgs hosting the extensions
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            IFS=$'\n' readarray -t repositories < <( echo $CANONICAL_EXTENSIONS | tr -d '\r' )
          
            # Sort out which repositories provide the necessary workflows first.
            filtered=()
            skipped=()
            echo -n "Looking up repositories (${#repositories[@]}): "
            for repository in ${repositories[@]}; do
                # TODO: for testing purposes we treat access issues as skipped repos
                match=$( ( gh workflow list --json path --jq '.[].path' --repo $repository | grep -E '.github/workflows/(manual-ci.yml|ci-manual.yml)' | wc -l ) || echo '0' )
                if [[ $match == '1' ]]; then
                    filtered+=( $repository )
                else
                    skipped+=( $repository )
                fi
                echo -n '.'
            done
            filtered=( $( printf '%s\n' "${filtered[@]}" | sort ) )
            skipped=( $( printf '%s\n' "${skipped[@]}" | sort ) )
            echo ''
  
            # Report the skipped repositories.
            echo "Skipping due to missing target workflows (${#skipped[@]} repo(s))"
            for repository in ${skipped[@]}; do
                echo "    -- ${repository##*/}"
            done

            # TODO: further relocate the test script.
